ANALYSIS_MODES = [
    {
        "id": "proportions",
        "title_key": "analysis.mode.proportions",
        "icon_name": "chart.bar.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 10,
        "is_enabled": True,
    },
    {
        "id": "aesthetics",
        "title_key": "analysis.mode.aesthetics",
        "icon_name": "brain.head.profile",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 20,
        "is_enabled": True,
    },
    {
        "id": "glow-up-coach",
        "title_key": "analysis.mode.glowUpCoach",
        "icon_name": "sparkles",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": True,
        "sort_order": 30,
        "is_enabled": True,
    },
    {
        "id": "look-archetype",
        "title_key": "analysis.mode.lookArchetype",
        "icon_name": "theatermasks.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 40,
        "is_enabled": True,
    },
    {
        "id": "best-photo-selector",
        "title_key": "analysis.mode.bestPhotoSelector",
        "icon_name": "checkmark.seal.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 50,
        "is_enabled": True,
    },
    {
        "id": "best-angle-finder",
        "title_key": "analysis.mode.bestAngleFinder",
        "icon_name": "viewfinder",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 60,
        "is_enabled": True,
    },
    {
        "id": "dating-profile-score",
        "title_key": "analysis.mode.datingProfileScore",
        "icon_name": "heart.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 70,
        "is_enabled": True,
    },
    {
        "id": "instagram-profile-score",
        "title_key": "analysis.mode.instagramProfileScore",
        "icon_name": "square.grid.3x3.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 80,
        "is_enabled": True,
    },
]

ANALYSIS_METRIC_TEMPLATES = [
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "main-photo-suitability",
        "title_key": "analysis.photoOptimization.metric.mainPhotoSuitability",
        "icon_name": "heart.fill",
        "sort_order": 10,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "first-swipe-read",
        "title_key": "analysis.photoOptimization.metric.firstSwipeRead",
        "icon_name": "sparkles",
        "sort_order": 20,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "approachability",
        "title_key": "analysis.photoOptimization.metric.approachability",
        "icon_name": "bubble.left.and.bubble.right.fill",
        "sort_order": 30,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "confidence-signal",
        "title_key": "analysis.photoOptimization.metric.confidenceSignal",
        "icon_name": "bolt.fill",
        "sort_order": 40,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "trust-signal",
        "title_key": "analysis.photoOptimization.metric.trustSignal",
        "icon_name": "checkmark.seal.fill",
        "sort_order": 50,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "style-signal",
        "title_key": "analysis.photoOptimization.metric.styleSignal",
        "icon_name": "person.crop.square.fill",
        "sort_order": 60,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "conversation-hook",
        "title_key": "analysis.photoOptimization.metric.conversationHook",
        "icon_name": "text.bubble.fill",
        "sort_order": 70,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "photo-context",
        "title_key": "analysis.photoOptimization.metric.photoContext",
        "icon_name": "rectangle.stack.fill",
        "sort_order": 80,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "dating_profile",
        "metric_id": "red-flag-risk",
        "title_key": "analysis.photoOptimization.metric.redFlagRisk",
        "icon_name": "exclamationmark.triangle.fill",
        "sort_order": 90,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "profile_plan",
        "metric_id": "photo-mix",
        "title_key": "analysis.photoOptimization.metric.photoMix",
        "icon_name": "rectangle.stack.fill",
        "sort_order": 100,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "profile_plan",
        "metric_id": "profile-role",
        "title_key": "analysis.photoOptimization.metric.profileRole",
        "icon_name": "person.crop.square.fill",
        "sort_order": 110,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "profile_plan",
        "metric_id": "message-bait",
        "title_key": "analysis.photoOptimization.metric.messageBait",
        "icon_name": "text.bubble.fill",
        "sort_order": 120,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "profile_plan",
        "metric_id": "missing-shot",
        "title_key": "analysis.photoOptimization.metric.missingShot",
        "icon_name": "camera.fill",
        "sort_order": 130,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "profile_plan",
        "metric_id": "opener-angle",
        "title_key": "analysis.photoOptimization.metric.openerAngle",
        "icon_name": "wand.and.stars",
        "sort_order": 140,
        "is_enabled": True,
    },
    {
        "mode_id": "dating-profile-score",
        "section": "profile_plan",
        "metric_id": "avoid-profile",
        "title_key": "analysis.photoOptimization.metric.avoidProfile",
        "icon_name": "xmark.octagon.fill",
        "sort_order": 150,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "profile-crop",
        "title_key": "analysis.photoOptimization.metric.profileCrop",
        "icon_name": "crop",
        "sort_order": 10,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "thumbnail-impact",
        "title_key": "analysis.photoOptimization.metric.thumbnailImpact",
        "icon_name": "viewfinder",
        "sort_order": 20,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "profile-icon-energy",
        "title_key": "analysis.photoOptimization.metric.profileIconEnergy",
        "icon_name": "person.crop.square.fill",
        "sort_order": 30,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "first-impression",
        "title_key": "analysis.photoOptimization.metric.firstImpression",
        "icon_name": "sparkles",
        "sort_order": 40,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "feed-fit",
        "title_key": "analysis.photoOptimization.metric.feedFit",
        "icon_name": "square.grid.3x3.fill",
        "sort_order": 50,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "story-thumbnail",
        "title_key": "analysis.photoOptimization.metric.storyThumbnail",
        "icon_name": "circle.grid.cross.fill",
        "sort_order": 60,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "scroll-stop-power",
        "title_key": "analysis.photoOptimization.metric.scrollStopPower",
        "icon_name": "bolt.fill",
        "sort_order": 70,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "visual-consistency",
        "title_key": "analysis.photoOptimization.metric.visualConsistency",
        "icon_name": "slider.horizontal.3",
        "sort_order": 80,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "instagram_profile",
        "metric_id": "color-mood",
        "title_key": "analysis.photoOptimization.metric.colorMood",
        "icon_name": "slider.horizontal.3",
        "sort_order": 90,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "content_plan",
        "metric_id": "caption-direction",
        "title_key": "analysis.photoOptimization.metric.captionDirection",
        "icon_name": "text.bubble.fill",
        "sort_order": 100,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "content_plan",
        "metric_id": "grid-anchor",
        "title_key": "analysis.photoOptimization.metric.gridAnchor",
        "icon_name": "square.grid.3x3.fill",
        "sort_order": 110,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "content_plan",
        "metric_id": "story-reply-trigger",
        "title_key": "analysis.photoOptimization.metric.storyReplyTrigger",
        "icon_name": "text.bubble.fill",
        "sort_order": 120,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "content_plan",
        "metric_id": "carousel-use",
        "title_key": "analysis.photoOptimization.metric.carouselUse",
        "icon_name": "rectangle.stack.fill",
        "sort_order": 130,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "content_plan",
        "metric_id": "posting-rhythm",
        "title_key": "analysis.photoOptimization.metric.postingRhythm",
        "icon_name": "calendar",
        "sort_order": 140,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "content_plan",
        "metric_id": "filter-risk",
        "title_key": "analysis.photoOptimization.metric.filterRisk",
        "icon_name": "exclamationmark.triangle.fill",
        "sort_order": 150,
        "is_enabled": True,
    },
    {
        "mode_id": "instagram-profile-score",
        "section": "content_plan",
        "metric_id": "posting-fix",
        "title_key": "analysis.photoOptimization.metric.postingFix",
        "icon_name": "wand.and.stars",
        "sort_order": 160,
        "is_enabled": True,
    },
]
