ANALYSIS_MODES = [
    {
        "id": "proportions",
        "title_key": "analysis.mode.proportions",
        "icon_name": "chart.bar.fill",
        "badge_key": "analysis.badge.unlimited",
        "badge_type": "unlimited",
        "badge_color": "#34D15C",
        "is_highlighted": False,
        "sort_order": 10,
        "is_enabled": True,
    },
    {
        "id": "aesthetics",
        "title_key": "analysis.mode.aesthetics",
        "icon_name": "brain.head.profile",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 20,
        "is_enabled": True,
    },
    {
        "id": "glow-up-coach",
        "title_key": "analysis.mode.glowUpCoach",
        "icon_name": "sparkles",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": True,
        "sort_order": 30,
        "is_enabled": True,
    },
    {
        "id": "look-archetype",
        "title_key": "analysis.mode.lookArchetype",
        "icon_name": "theatermasks.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 40,
        "is_enabled": True,
    },
    {
        "id": "best-photo-selector",
        "title_key": "analysis.mode.bestPhotoSelector",
        "icon_name": "checkmark.seal.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 50,
        "is_enabled": True,
    },
    {
        "id": "best-angle-finder",
        "title_key": "analysis.mode.bestAngleFinder",
        "icon_name": "viewfinder",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 60,
        "is_enabled": True,
    },
    {
        "id": "dating-profile-score",
        "title_key": "analysis.mode.datingProfileScore",
        "icon_name": "heart.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 70,
        "is_enabled": True,
    },
    {
        "id": "instagram-profile-score",
        "title_key": "analysis.mode.instagramProfileScore",
        "icon_name": "square.grid.3x3.fill",
        "badge_key": "analysis.badge.proScan",
        "badge_type": "pro_scan",
        "badge_color": "#6175FF",
        "is_highlighted": False,
        "sort_order": 80,
        "is_enabled": True,
    },
]
